/* tslint:disable */
/* eslint-disable */
/**
 * example
 * The betting API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Tenant } from "./Tenant";
import { TenantFromJSON, TenantFromJSONTyped, TenantToJSON } from "./Tenant";

/**
 *
 * @export
 * @interface CreateManyTenantDto
 */
export interface CreateManyTenantDto {
  /**
   *
   * @type {Array<Tenant>}
   * @memberof CreateManyTenantDto
   */
  bulk: Array<Tenant>;
}

/**
 * Check if a given object implements the CreateManyTenantDto interface.
 */
export function instanceOfCreateManyTenantDto(
  value: object
): value is CreateManyTenantDto {
  if (!("bulk" in value) || value["bulk"] === undefined) return false;
  return true;
}

export function CreateManyTenantDtoFromJSON(json: any): CreateManyTenantDto {
  return CreateManyTenantDtoFromJSONTyped(json, false);
}

export function CreateManyTenantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateManyTenantDto {
  if (json == null) {
    return json;
  }
  return {
    bulk: (json["bulk"] as Array<any>).map(TenantFromJSON),
  };
}

export function CreateManyTenantDtoToJSON(
  value?: CreateManyTenantDto | null
): any {
  if (value == null) {
    return value;
  }
  return {
    bulk: (value["bulk"] as Array<any>).map(TenantToJSON),
  };
}
