/* tslint:disable */
/* eslint-disable */
/**
 * example
 * The betting API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import { UserFromJSON, UserFromJSONTyped, UserToJSON } from "./User";

/**
 *
 * @export
 * @interface CreateManyUserDto
 */
export interface CreateManyUserDto {
  /**
   *
   * @type {Array<User>}
   * @memberof CreateManyUserDto
   */
  bulk: Array<User>;
}

/**
 * Check if a given object implements the CreateManyUserDto interface.
 */
export function instanceOfCreateManyUserDto(
  value: object
): value is CreateManyUserDto {
  if (!("bulk" in value) || value["bulk"] === undefined) return false;
  return true;
}

export function CreateManyUserDtoFromJSON(json: any): CreateManyUserDto {
  return CreateManyUserDtoFromJSONTyped(json, false);
}

export function CreateManyUserDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateManyUserDto {
  if (json == null) {
    return json;
  }
  return {
    bulk: (json["bulk"] as Array<any>).map(UserFromJSON),
  };
}

export function CreateManyUserDtoToJSON(value?: CreateManyUserDto | null): any {
  if (value == null) {
    return value;
  }
  return {
    bulk: (value["bulk"] as Array<any>).map(UserToJSON),
  };
}
