/* tslint:disable */
/* eslint-disable */
/**
 * example
 * The betting API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { User } from "./User";
import { UserFromJSON, UserFromJSONTyped, UserToJSON } from "./User";

/**
 *
 * @export
 * @interface GetManyUserResponseDto
 */
export interface GetManyUserResponseDto {
  /**
   *
   * @type {Array<User>}
   * @memberof GetManyUserResponseDto
   */
  data: Array<User>;
  /**
   *
   * @type {number}
   * @memberof GetManyUserResponseDto
   */
  count: number;
  /**
   *
   * @type {number}
   * @memberof GetManyUserResponseDto
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof GetManyUserResponseDto
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof GetManyUserResponseDto
   */
  pageCount: number;
}

/**
 * Check if a given object implements the GetManyUserResponseDto interface.
 */
export function instanceOfGetManyUserResponseDto(
  value: object
): value is GetManyUserResponseDto {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("page" in value) || value["page"] === undefined) return false;
  if (!("pageCount" in value) || value["pageCount"] === undefined) return false;
  return true;
}

export function GetManyUserResponseDtoFromJSON(
  json: any
): GetManyUserResponseDto {
  return GetManyUserResponseDtoFromJSONTyped(json, false);
}

export function GetManyUserResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetManyUserResponseDto {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(UserFromJSON),
    count: json["count"],
    total: json["total"],
    page: json["page"],
    pageCount: json["pageCount"],
  };
}

export function GetManyUserResponseDtoToJSON(
  value?: GetManyUserResponseDto | null
): any {
  if (value == null) {
    return value;
  }
  return {
    data: (value["data"] as Array<any>).map(UserToJSON),
    count: value["count"],
    total: value["total"],
    page: value["page"],
    pageCount: value["pageCount"],
  };
}
