/* tslint:disable */
/* eslint-disable */
/**
 * example
 * The betting API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Array<Tenant> } from './Array&lt;Tenant&gt;';
import {
    instanceOfArray<Tenant>,
    Array<Tenant>FromJSON,
    Array<Tenant>FromJSONTyped,
    Array<Tenant>ToJSON,
} from './Array&lt;Tenant&gt;';
import type { GetManyTenantResponseDto } from './GetManyTenantResponseDto';
import {
    instanceOfGetManyTenantResponseDto,
    GetManyTenantResponseDtoFromJSON,
    GetManyTenantResponseDtoFromJSONTyped,
    GetManyTenantResponseDtoToJSON,
} from './GetManyTenantResponseDto';

/**
 * @type GetManyBaseTenantControllerTenant200Response
 * 
 * @export
 */
export type GetManyBaseTenantControllerTenant200Response = Array<Tenant> | GetManyTenantResponseDto;

export function GetManyBaseTenantControllerTenant200ResponseFromJSON(json: any): GetManyBaseTenantControllerTenant200Response {
    return GetManyBaseTenantControllerTenant200ResponseFromJSONTyped(json, false);
}

export function GetManyBaseTenantControllerTenant200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetManyBaseTenantControllerTenant200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfArray<Tenant>(json)) {
        return Array<Tenant>FromJSONTyped(json, true);
    }
    if (instanceOfGetManyTenantResponseDto(json)) {
        return GetManyTenantResponseDtoFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetManyBaseTenantControllerTenant200ResponseToJSON(value?: GetManyBaseTenantControllerTenant200Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfArray<Tenant>(value)) {
        return Array<Tenant>ToJSON(value as Array<Tenant>);
    }
    if (instanceOfGetManyTenantResponseDto(value)) {
        return GetManyTenantResponseDtoToJSON(value as GetManyTenantResponseDto);
    }

    return {};
}

