/* tslint:disable */
/* eslint-disable */
/**
 * example
 * The betting API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Array<User> } from './Array&lt;User&gt;';
import {
    instanceOfArray<User>,
    Array<User>FromJSON,
    Array<User>FromJSONTyped,
    Array<User>ToJSON,
} from './Array&lt;User&gt;';
import type { GetManyUserResponseDto } from './GetManyUserResponseDto';
import {
    instanceOfGetManyUserResponseDto,
    GetManyUserResponseDtoFromJSON,
    GetManyUserResponseDtoFromJSONTyped,
    GetManyUserResponseDtoToJSON,
} from './GetManyUserResponseDto';

/**
 * @type GetManyBaseUserControllerUser200Response
 * 
 * @export
 */
export type GetManyBaseUserControllerUser200Response = Array<User> | GetManyUserResponseDto;

export function GetManyBaseUserControllerUser200ResponseFromJSON(json: any): GetManyBaseUserControllerUser200Response {
    return GetManyBaseUserControllerUser200ResponseFromJSONTyped(json, false);
}

export function GetManyBaseUserControllerUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetManyBaseUserControllerUser200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfArray<User>(json)) {
        return Array<User>FromJSONTyped(json, true);
    }
    if (instanceOfGetManyUserResponseDto(json)) {
        return GetManyUserResponseDtoFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetManyBaseUserControllerUser200ResponseToJSON(value?: GetManyBaseUserControllerUser200Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfArray<User>(value)) {
        return Array<User>ToJSON(value as Array<User>);
    }
    if (instanceOfGetManyUserResponseDto(value)) {
        return GetManyUserResponseDtoToJSON(value as GetManyUserResponseDto);
    }

    return {};
}

